app/blog/urls.py
from django.urls import path
from django.core.exceptions import PermissionDenied
from . import views

def staff_user(function):
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied
    return wrap



app_name = 'blogs'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('admin-view/', views.admin_blog_list, name='admin_blog_list'),
    path('create/', views.write_blog_view, name='blog_create'),
    path('<int:pk>/detail', views.blog_detail, name='blog_detail'),
    path('admin-view/<int:pk>/detail', views.admin_blog_detail, name='admins_blog_detail'),
    path('<int:pk>/update', views.blog_update_view, name='blog_update'),
    path('<int:pk>/delete', views.blog_delete, name='blog_delete'),
    path('<int:pk>/approve', views.blog_approval, name='blog_approval'),
    path('comment/<int:pk>/comment', views.create_comment, name='add_blog_comment'),
    path('comment/<int:pk>/delete', views.comment_delete, name='delete_blog_comment'),
    path('search/', views.search, name='search'),
    path('about-us/', views.about_us, name='about_us'),
]

app/config/urls.py
# Deleveoped
# Fahad Md Kamal
# NCC ID: 00171328



from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('register/', user_views.register, name= 'register'),
    path('profile/', user_views.profile, name= 'profile'),
    path('user-profile/<int:pk>/', user_views.user_detail, name='user_profile' ),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='index.html'), name='logout'),
    path('vehicle/', include('vehicle.urls', namespace='vehicle')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('fleet/', include('fleet.urls', namespace='fleet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/fleet/urls.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django.urls import path
from . import views

app_name = 'fleet'

urlpatterns = [
       
    path(
        '',
        views.fleet_view,
        name= 'fleets'),

    path(
        'admin-view/',
        views.admin_fleet_view,
        name= 'admin_fleet_view'),
       
    path(
        'detail/<int:pk>/',
        views.fleet_detail_view,
        name= 'detail_fleet'),
       
    path(
        'detail/<int:pk>/<int:car_pk>',
        views.fleet_detail_view,
        name= 'detail_fleet'),
       
    path(
        'add-vehicle/<int:pk>',
        views.add_to_fleet,
        name= 'add_to_fleet'),
       
    path(
        'new-fleet/',
        views.new_fleet,
        name= 'new_fleet'),
       
    path(
        'existing-fleet/<int:pk>/',
        views.existing_fleet,
        name= 'existing_fleet'),
        
    path(
        'remove-vehicle/<int:fleet_pk>/<int:vehicle_pk>',
        views.remove_from_fleet,
        name= 'remove_from_fleet'),
        
    path(
        'cancel-fleet/<int:pk>/',
        views.cancel_fleet,
        name= 'cancel_fleet'),
        
    path(
        'remove-fleet/<int:pk>/',
        views.remove_fleet,
        name= 'remove_fleet'),
        
    path(
        'approve-fleet/<int:pk>/',
        views.approve_fleet,
        name= 'approve_fleet'),
        
    path(
        'freeze-fleet/<int:pk>/',
        views.freeze_fleet,
        name= 'freeze_fleet'),

    path(
        '<int:pk>/', 
        views.checkout, 
        name='checkout' ),

    path(
        'update-record/<int:pk>/<str:token>', 
        views.update_payment_record, 
        name='update_record' ),

    path(
        'report/<int:pk>', 
        views.report_generator, 
        name='report_generator' ),

        
]

app/vehicle/urls.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django.urls import path
from . import views

app_name = 'vehicle'

urlpatterns = [
       
    path('',
        views.vehicle_list_view, 
        name= 'vehicle_list'),
    
    path('admin-view/', 
        views.admin_vehicle_view, 
        name= 'admin_vehicle'),
    
    path('owner-view/', 
        views.owner_vehicle_list, 
        name= 'owner_vehicle_list'),
    
    path('search-vehicles/', 
        views.search_vehicle, 
        name= 'search_vehicle'),

    path('register/', 
        views.vehicle_registration, 
        name= 'reg_vehicle'),
    
    path('<int:pk>/', 
        views.vehicle_detail_view, 
        name= 'detail_vehicle'),
    
    path('<int:pk>/approve', 
        views.approve_vehicle, 
        name= 'approve_vehicle'),
    
    path('<int:pk>/freeze', 
        views.freeze_vehicle, 
        name= 'freeze_vehicle'),
    
    path('<int:pk>/update/', 
        views.vehicle_update_view, 
        name= 'update_vehicle'),
    
    path('<int:pk>/delete/', 
        views.vehicel_delete_view, 
        name= 'delete_vehicle'),
]

app/vehicle/models.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

#pylint: disable = no-member, unused-variable

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
import os, random, datetime
from PIL import Image



def photo_path(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    print(basefilename, file_extension)
    vehicle_reg = instance.reg_no
    date = datetime.datetime.now()
    return f'vehicle_pics/{vehicle_reg}/{date}-{vehicle_reg}{file_extension}'



class Vehicle(models.Model):
    SM = 0
    MD = 1
    LG = 2
    VN = 3
    VEHICLE_CATEGORIES = [
        (SM, 'Small'),
        (MD, 'Medium'),
        (LG, 'Large'),
        (VN, 'Van'),
    ]

    VEHICLE_MODEL = [
        ( 0, 'Other'),
        ( 1, 'Audi'),
        ( 2, 'BMW'),
        ( 3, 'Chevrolet'),
        ( 4, 'Ford'),
        ( 5, 'Honda'),
        ( 6, 'Hyundai'),
        ( 7, 'Jeep'),
        ( 8, 'Kia'),
        ( 9, 'Lexus'),
        ( 10, 'Mazda'),
        ( 11, 'Mercedes-Benz'),
        ( 12, 'Mitsubishi'),
        ( 13, 'Nissan'),
        ( 14, 'Renault'),
        ( 15, 'Suzuki'),
        ( 16, 'Subaru'),
        ( 17, 'Tata'),
        ( 18, 'Toyota'),
        ( 19, 'VolksWagen'),
        ( 20, 'Volvo'),
    ]

    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vehicel_owner')
    model_name      = models.IntegerField(choices=VEHICLE_MODEL, default=0)
    model_year      = models.DateField(blank=True, null=True)
    reg_no          = models.CharField(max_length=20, unique=True)
    vehicle_type    = models.IntegerField(choices=VEHICLE_CATEGORIES, default=SM)
    added_on        = models.DateField(auto_now_add=True)
    rent            = models.PositiveIntegerField(default = 2000)
    capacity        = models.PositiveIntegerField(default=2)
    is_freezed      = models.BooleanField(default=False)
    is_approved     = models.BooleanField(default=False)
    is_booked       = models.BooleanField(default=False)
    booked_date     = models.DateTimeField( auto_now=True, blank=True, null=True)
    is_hired        = models.BooleanField(default=False)
    image           = models.ImageField(default='default_vehicle.png', upload_to =photo_path)

    class Meta:
        ordering = ['-is_approved','-added_on']


    def get_absolute_url(self):
        return reverse_lazy('vehicle:detail_vehicle', kwargs={'pk': self.pk})


    def approve_vehicle(self):
        self.is_approved = not self.is_approved
        self.save()

    def freeze_vehicle(self):
        self.is_freezed = not self.is_freezed
        self.save()


    def save(self, *args, **kwargs):
        super(Vehicle, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 350:
            output_size = (400, 450)
            img.thumbnail(output_size)
            img.save(self.image.path)


    @staticmethod
    def hire_vehicle(self):
        self.is_hired = not self.is_hired
        self.save()


    @staticmethod
    def booked(self):
        self.is_booked  = True
        self.booked_date = datetime.datetime.now()
        self.save()

    @staticmethod
    def unbook(self):
        self.is_booked  = False
        self.booked_date = datetime.datetime.now()
        self.save()


    def __str__(self):
        return  self.reg_no
        

app/vehicle/forms.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from . import models



class DateInputForm(forms.DateTimeInput):
    input_type = 'date'


class vehicle_reg_form(forms.ModelForm):

    reg_no = forms.CharField(
        label = 'Registration no: ',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. VXN-854'}))
    
    capacity = forms.CharField(
        label = 'Capacity: ',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. 4 persons'}))
    
    rent = forms.CharField(
        label = 'Rent/month: ',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. 80000'}))

    class Meta:
        model = models.Vehicle
        fields = ('model_name',
                  'reg_no', 
                  'model_year',
                  'capacity',
                  'rent',
                  'image',
                  'vehicle_type',
                  )

        widgets = {
            'reg_no': forms.TextInput(
                    attrs=
                    {'class':'form-control', 'placeholder':'Reg No: VMX 19654'}),
            'model_year': DateInputForm()
        }


class vehicle_model_form(forms.ModelForm):

    model_name= forms.Select(attrs={'name':'vehicle_model'})

    class Meta:
        model = models.Vehicle
        fields = ('model_name',)


    

app/vehicle/views.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

#pylint: disable = no-member, unused-variable, undefined-variable
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.mail import send_mail

from datetime import date, datetime


import re

from . import models, forms
from fleet.models import Fleet


def vehicle_list_view(request):
    template        = 'vehicle/vehicle_list.html'
    fleet_id        = request.session.get('fleet_id', None)
    fleet_cars      = ''
    if fleet_id:
        fleet       = get_object_or_404(Fleet, pk=fleet_id)
        fleet_cars  = fleet.get_fleet_vehicles()

    CarsList        = models.Vehicle.objects.filter(is_freezed = False, 
                                is_approved = True, 
                                is_hired = False)

    page = request.GET.get('page', 1)
    paginator = Paginator(CarsList, 5)
    try:
        cars = paginator.page(page)
    except PageNotAnInteger:
        cars = paginator.page(1)
    except EmptyPage:
        cars = paginator.page(paginator.num_pages)

    context = {
        'cars'          : cars,
        'page_heading'  : 'Available',
        'vehicle_list'  : models.Vehicle.objects.all(),
        'fleet_cars'    : fleet_cars,
        'form'          : forms.vehicle_model_form()
    }
    return render(request, template, context)


def vehicle_detail_view(request, pk):
    template        = 'vehicle/vehicle_detail.html'
    context = {
        'car':get_object_or_404(models.Vehicle, pk=pk)
    }
    return render(request, template, context)


@login_required
def vehicle_registration(request):
    template        = 'vehicle/vehicle_form.html'
    if request.method == 'POST':
        form = forms.vehicle_reg_form(request.POST, request.FILES)
        if form.is_valid():
            vehicle = form.save(commit=False)
            model_date = form.cleaned_data['model_year']
            # Check The Date
            if (model_date - datetime.now().date()).days > 0:
                messages.warning(request, "Invalid Date")
            else:
                vehicle.owner = request.user
                vehicle = form.save()
                messages.success(request, f'Vehicle {vehicle.reg_no} registared successfully. We will notify you when approved')
                return HttpResponseRedirect(vehicle.get_absolute_url())
    else:
        form = forms.vehicle_reg_form()
    context = {
        'form': form,
        'state': 'Register'
    }
    return render(request, template, context)


@login_required
def vehicle_update_view(request, pk):
    template        = 'vehicle/vehicle_form.html'
    vehicle         = get_object_or_404(models.Vehicle, id = pk)
    user            = request.user
    if user.is_staff or user == vehicle.owner:
        if request.method == 'POST':
            form     = forms.vehicle_reg_form(request.POST, instance = vehicle)
            if form.is_valid():
                vehcile = form.save( commit= False)
                model_date = form.cleaned_data['model_year']
                # Check The Date
                if (model_date - datetime.now().date()).days > 0:
                    messages.warning(request, "Invalid Date")
                else:
                    vehcile.is_approved = False
                    vehcile.save()
                    messages.info(request, f'Vehicle {vehicle.reg_no} updated successfully')
                    return HttpResponseRedirect(vehicle.get_absolute_url())
            else:
                messages.error(request, 'Failed to update vehicle')
        else:
            form = forms.vehicle_reg_form(instance=vehicle)
        context = {
            'form':form,
            'state': 'Update'
        }
        return render(request, template, context)
    else:
        messages.error(request, 'You have no permission to update this vehicle')
        return HttpResponseRedirect(vehicle.get_absolute_url())


@login_required
def vehicel_delete_view(request, pk):
    template        = 'vehicle/vehicle_confirm_delete.html'
    car             = get_object_or_404(models.Vehicle, id = pk)
    user            = request.user
    if user.is_staff or car.owner == user:
        if request.method == 'POST':
            car.delete()
            messages.info(request, 'Vehicle deleted successfully')
            return redirect ('vehicle:vehicle_list')
        else:
            messages.error(request, 'Failed to delete the vehicle')
            context = {
                'car':car
            }
            return render(request, template, context)
    else:
        messages.error(request, 'You have no permission')
        return HttpResponseRedirect(car.get_absolute_url())   


def admin_vehicle_view(request):
    template    = 'vehicle/vehicle_admin.html'
    cars_list   = models.Vehicle.objects.all()
    context = {
        'cars_list': cars_list
    }
    return render(request, template, context)


def approve_vehicle(request, pk):
    vehicle = get_object_or_404(models.Vehicle, pk =pk)
    vehicle.approve_vehicle()
    
    send_mail('Vehicle Approved',
        f'Your vehicle {vehicle.reg_no} has been approved.',
        'randomfahad@gmail.com', [vehicle.owner.email], fail_silently=True )
    return redirect('vehicle:admin_vehicle')


def freeze_vehicle(request, pk):
    vehicle = get_object_or_404(models.Vehicle, pk =pk)
    vehicle.freeze_vehicle()
    return redirect('vehicle:admin_vehicle')


def owner_vehicle_list(request):
    template        = 'vehicle/vehicle_list.html'
    CarsList        = models.Vehicle.objects.filter(owner = request.user)
    context = {
        'cars': CarsList,
        'page_heading' : request.user.username + '\'s',
        'form'          : forms.vehicle_model_form()
    }
    return render (request, template, context)


def search_vehicle(request):
    template        = 'vehicle/vehicle_list.html'
    vehicle_list        = models.Vehicle.objects.filter(is_approved = True)

    vehicel_type    = request.GET.get('vehicel_type', None)
    model_name   = request.GET.get('model_name', None)
    query_text      = request.GET.get('query_text', None)

    if query_text != '' and query_text is not None:
        CarsList = vehicle_list.filter(reg_no__icontains=query_text)

    elif vehicel_type != '' and vehicel_type is not None:
        CarsList = vehicle_list.filter(vehicle_type=vehicel_type)

    elif model_name != '':
        try:
            CarsList = vehicle_list.filter(model_name=model_name)
        except:
            CarsList = None

    context = {
        'cars':CarsList,
        'page_heading' : 'Filtered',
        'form' : forms.vehicle_model_form()
    }
    return render (request, template, context)    

app/vehicle/templates/vehicle/_detail_vehicle.html
<p class="h3">{{car.get_model_name_display}} - {{car.model_year|date:"Y"}}</p>

          <div class="table-responsivv">  
        <table class="table table-striped vh_table">
          <legend class="my-5"></legend>
                <tbody>
                  <tr>
                    <td colspan="2"><img class="mx-auto d-block vehicle_img" src="{{ car.image.url }}" alt="{{ car.model_name }}"></td>
                  </tr>
                  <tr class="table-success">
                    <td>Owner:</td>
                    <td> <i class="fa fa-user"></i> <a href="{% url 'user_profile' car.owner.pk %}"> {{car.owner.username}}</a></td>
                  </tr>
                  <tr class="table-danger">
                    <td>Model Name: </td>
                    <td>{{car.get_model_name_display}}</td>
                  </tr>
                  <tr class="table-primary">
                    <td>Model Year: </td>
                    <td>{{car.model_year|date:"Y"}}</td>
                  </tr>
                  <tr class="table-info">
                    <td>Registration No: </td>
                    <td>"{{car.reg_no}}"</td>
                  </tr>
                  <tr class="table-warning">
                    <td>Category</td>
                    <td>{{car.get_vehicle_type_display}}</td>
                  </tr>
                  <tr class="table-danger">
                    <td>Status</td>
                    <td>{% if car.is_booked %} Booked {% elif car.is_hired %} Hired {% else %} Available {% endif %}</td>
                  </tr>
                  <tr class="table-primary">
                    <td>Capacity</td>
                    <td><i class="fas fa-chair"></i> {{car.capacity}}</td>
                  </tr>
                  <tr class="table-warning">
                    <td>Rent / month</td>
                    <td>&#2547; {{car.rent}}</td>
                  </tr>
                  <tr class="table-dark">
                    <td class="text-dark">Registared Since</td>
                    <td class="text-dark">{{ car.added_on|date:"d M Y" }}</td>
                  </tr>
                </tbody>
              </table>
            </div>

app/vehicle/templates/vehicle/_list_vehicle.html
<a class="my-2 text-decoration-none text-dark" href="{% url 'vehicle:detail_vehicle' car.pk %}">
        <div class="card-header h3">{{car.get_model_name_display}} - {{car.model_year|date:"Y"}}</div>
        <div class="container p-3">
                <img class="rounded mx-auto d-block my-5" src="{{ car.image.url }}" alt="{{ car.model_name }}">
                <table class="table table-hover text-center  vh_table">
                    <tr class="table-success">
                        <td>Model:</td>
                        <td class="font-weight-bolder "> {{ car.get_model_name_display }} </td>
                    </tr>
                    <tr class="table-info">
                        <td>Capacity:</td>
                        <td class="font-weight-bolder "> {{ car.capacity}} </td>
                    </tr>
                    <tr class="table-warning">
                        <td>Reg No:</td>
                        <td class="font-weight-bolder ">{{ car.reg_no }}</td>
                    </tr>
                    <tr class="table-danger">
                        <td>Category:</td>
                        <td class="font-weight-bolder text-dark ">{{car.get_vehicle_type_display}}</td>
                    </tr>
                </table>
                
   
            </div>
    </a>

app/vehicle/templates/vehicle/vehicle_admin.html
{% extends 'vehicle/vehicle_base.html' %}

{% block vehicle_content%}


    <!-- <div class="col-sm-12 col-md-8 col-lg-10"> -->
            {% if not user.is_staff %}
   <p class="display-3 container"> Sorry !! Only admins and moderators can visit this page</p>

{% else %}

<div class="p-5">
    <table id="table_id" class="display table">
        <thead>
            <tr>
                <th>Owner</th>
                <th>Model</th>
                <th>Reg. No.</th>
                <th>Category</th>
                <th>Status</th>
                <th>Capacity</th>
                <th>Rent / month</th>
                <th>Joined Since</th>
                <th ></th>
            </tr>
        </thead>
        <tbody>
            {% if cars_list %}
                {% for car in cars_list %}
                <tr>
                    <td><i class="fa fa-user"></i> {{car.owner.username}}</td>
                    <td>{{car.get_model_name_display}} - {{car.model_year|date:"Y"}}</td>
                    <td>{{car.reg_no}}</td>
                    <td>{{car.get_vehicle_type_display}}</td>
                    <td>{% if car.is_hired %} Hired {% else %} Available {% endif %}</td>
                    <td>{{ car.capacity}}</td>
                    <td>{{car.rent}}</td>
                    <td>{{ car.added_on|date:"d M Y" }}</td>
                    <td>
                        <div class="btn-group">
                            {% if not car.is_approved %}
                                <a class="btn btn-success" href="{% url 'vehicle:approve_vehicle' car.pk %}">Approve</a>
                                <a class="btn btn-danger" href="{% url 'vehicle:delete_vehicle' car.pk %}">Reject</a>
                            {% else %}
                                {% if not car.is_freezed %}
                                    <a class="btn btn-warning" href="{% url 'vehicle:freeze_vehicle' car.pk %}">Freeze</a>
                                {% else %}
                                    <a class="btn btn-success" href="{% url 'vehicle:freeze_vehicle' car.pk %}">Free</a>
                                {% endif %}
                                <a class="btn btn-primary" href="{% url 'vehicle:detail_vehicle' car.pk %}">Detail</a>
                                <a class="btn btn-danger" href="{% url 'vehicle:delete_vehicle' car.pk %}">Delete</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

                    </div>
              
{% endif %}


                <!-- </div> -->




{% endblock  %}

app/vehicle/templates/vehicle/vehicle_detail.html
{% extends 'vehicle/vehicle_base.html' %}
{% load crispy_forms_tags %}

{% block vehicle_content%}


<!-- Jumbotron -->
<div class="jumbotron col-sm-10 col-md-8 col-xl-6 offset-sm-1 offset-md-2 offset-xl-3">
        {% include 'vehicle/_detail_vehicle.html' %}
              <div class="btn-group d-flex justify-content-end">
                
                {% if car.owner == user or user.is_staff %}
                  <a class="btn btn-lg btn-warning" href="{% url 'vehicle:update_vehicle' car.pk %}">Edit</a>
                  {% endif %}

                <!-- {if not user.is_staff and not car.is_hired and car.is_approved } -->
                {%if user.user_profile.user_type == 0 and not user.is_staff %}
                  <a class="btn btn-lg btn-success" href="{% url 'fleet:add_to_fleet' car.pk %}">Book</a>
                {% endif %}
              </div>
      </div>
      <!-- Jumbotron -->

{% endblock  %}

app/vehicle/templates/vehicle/vehicle_list.html
{% extends 'vehicle/vehicle_base.html' %}
{% load crispy_forms_tags %}

{% block vehicle_content%}


<div class="col-xl-10 offset-xl-1">
    <div class="row">
<div class="col-sm-10 offset-sm-1 col-md-6 col-xl-6">
    {{msg}}
        {% if cars %}
                <div class="h3 text-center mt-5">All {{ page_heading }} Cars</div>
                {% for car in cars %}
                <div class="card ml-4 my-5">
                    {% include './_list_vehicle.html' %}
                    {% if car in fleet_cars %}
                    <div class="card-footer text-center">
                        <span class="h4 text-danger">In Fleet</span>
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
        
        
            {% else %}
                <p class="h2 text-info text-center mt-5">No car found</p>
            {% endif %}

            
            {% if cars.has_other_pages %}
            <nav class="Page navigation">
              <ul class="pagination">
                {% if cars.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ cars.previous_page_number }}">&laquo;</a>
                  </li>
                {% else %}
                  <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
            
                {% for i in cars.paginator.page_range %}
                  
                {% if cars.number == i %}
                    <li class="active text-danger">
                      <span>{{ i }} 
                        <span class="sr-only">(current)</span>
                      </span>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                  {% endif %}
            
                {% endfor %}
            
                {% if cars.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ cars.next_page_number }}">&raquo;</a>
                  </li>
                {% else %}
                  <li class="disabled">
                    <span>&raquo;</span>
                  </li>
                {% endif %}
            
              </ul>
            </nav>
            {% endif %}







        </div>
        
        <div class="col-md-3 d-sm-none d-md-block my-2 col-xl-3 offset-xl-1">
            <div class="h3 my-5">Filter Vehicle</div>
                
      <!-- Search card -->
      <div class="card mb-2">
        <p class="h3 p-2 text-dark card-title tempting-azure-gradient">
            Search
        </p>

        <!-- Search box -->
        <div class="card-body">
            <form action="{% url 'vehicle:search_vehicle' %}" method="get">
              <input class="form-control" type="text" name="query_text" placeholder="Registration No.." >
            <button class="btn btn-block badge-success badge-pill" type="submit">submit</button>
          </form> 
        </div>
        <!-- Search box -->

    </div>
    <!-- Search card -->

            <ul class="list-group">
                    <li class="list-group-item bg-primary">
                            <p class="h4 text-center text-light">Vehicle Type</p>
                    </li>
                <li class="list-group-item">
                    <a  class="btn btn-link" href="{% url 'vehicle:vehicle_list' %}" >All Cars 
                    </a> 
                </li>
                <li class="list-group-item">
                    <form action="{% url 'vehicle:search_vehicle' %}" method="get">
                        <input type="hidden" name="vehicel_type" value="0" >
                        <button class="btn btn-link" type="submit"> Small Car </button>
                    </form> 
                </li>
                <li class="list-group-item">
                    <form action="{% url 'vehicle:search_vehicle' %}" method="get">
                        <input type="hidden" name="vehicel_type" value="1" >
                        <button class="btn btn-link" type="submit"> Medium Car </button>
                    </form> 
                </li>
                <li class="list-group-item">
                    <form action="{% url 'vehicle:search_vehicle' %}" method="get">
                        <input type="hidden" name="vehicel_type" value="2" >
                        <button class="btn btn-link" type="submit"> Large Car </button>
                    </form>
                </li>
                <li class="list-group-item">
                    <form action="{% url 'vehicle:search_vehicle' %}" method="get">
                        <input type="hidden" name="vehicel_type" value="3" >
                        <button class="btn btn-link" type="submit"> All Vans </button>
                    </form> 
                </li>
            <!-- </ul>

            
            <ul class="list-group"> -->
                <li class="list-group-item divider" ></li>
                    <li class="list-group-item bg-primary">
                            <p class="h4 text-center text-light">Models</p>
                    </li>
            <li class="list-group-item">
                <form action="{% url 'vehicle:search_vehicle' %}" method="get">
                        {{ form|crispy }}
                <button class="btn btn-block badge-success badge-pill" type="submit">submit</button>
                </form> 
            </li>
    </ul>
        </div>
    </div>
    </div>





{% endblock  %}