app/blog/urls.py
from django.urls import path
from django.core.exceptions import PermissionDenied
from . import views

def staff_user(function):
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied
    return wrap



app_name = 'blogs'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('admin-view/', views.admin_blog_list, name='admin_blog_list'),
    path('create/', views.write_blog_view, name='blog_create'),
    path('<int:pk>/detail', views.blog_detail, name='blog_detail'),
    path('admin-view/<int:pk>/detail', views.admin_blog_detail, name='admins_blog_detail'),
    path('<int:pk>/update', views.blog_update_view, name='blog_update'),
    path('<int:pk>/delete', views.blog_delete, name='blog_delete'),
    path('<int:pk>/approve', views.blog_approval, name='blog_approval'),
    path('comment/<int:pk>/comment', views.create_comment, name='add_blog_comment'),
    path('comment/<int:pk>/delete', views.comment_delete, name='delete_blog_comment'),
    path('search/', views.search, name='search'),
    path('about-us/', views.about_us, name='about_us'),
]

app/config/urls.py
# Deleveoped
# Fahad Md Kamal
# NCC ID: 00171328



from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('register/', user_views.register, name= 'register'),
    path('profile/', user_views.profile, name= 'profile'),
    path('user-profile/<int:pk>/', user_views.user_detail, name='user_profile' ),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='index.html'), name='logout'),
    path('vehicle/', include('vehicle.urls', namespace='vehicle')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('fleet/', include('fleet.urls', namespace='fleet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/fleet/urls.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django.urls import path
from . import views

app_name = 'fleet'

urlpatterns = [
       
    path(
        '',
        views.fleet_view,
        name= 'fleets'),

    path(
        'admin-view/',
        views.admin_fleet_view,
        name= 'admin_fleet_view'),
       
    path(
        'detail/<int:pk>/',
        views.fleet_detail_view,
        name= 'detail_fleet'),
       
    path(
        'detail/<int:pk>/<int:car_pk>',
        views.fleet_detail_view,
        name= 'detail_fleet'),
       
    path(
        'add-vehicle/<int:pk>',
        views.add_to_fleet,
        name= 'add_to_fleet'),
       
    path(
        'new-fleet/',
        views.new_fleet,
        name= 'new_fleet'),
       
    path(
        'existing-fleet/<int:pk>/',
        views.existing_fleet,
        name= 'existing_fleet'),
        
    path(
        'remove-vehicle/<int:fleet_pk>/<int:vehicle_pk>',
        views.remove_from_fleet,
        name= 'remove_from_fleet'),
        
    path(
        'cancel-fleet/<int:pk>/',
        views.cancel_fleet,
        name= 'cancel_fleet'),
        
    path(
        'remove-fleet/<int:pk>/',
        views.remove_fleet,
        name= 'remove_fleet'),
        
    path(
        'approve-fleet/<int:pk>/',
        views.approve_fleet,
        name= 'approve_fleet'),
        
    path(
        'freeze-fleet/<int:pk>/',
        views.freeze_fleet,
        name= 'freeze_fleet'),

    path(
        '<int:pk>/', 
        views.checkout, 
        name='checkout' ),

    path(
        'update-record/<int:pk>/<str:token>', 
        views.update_payment_record, 
        name='update_record' ),

    path(
        'report/<int:pk>', 
        views.report_generator, 
        name='report_generator' ),

        
]

app/vehicle/models.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

#pylint: disable = no-member, unused-variable

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse_lazy
import os, random, datetime
from PIL import Image



def photo_path(instance, filename):
    basefilename, file_extension= os.path.splitext(filename)
    print(basefilename, file_extension)
    vehicle_reg = instance.reg_no
    date = datetime.datetime.now()
    return f'vehicle_pics/{vehicle_reg}/{date}-{vehicle_reg}{file_extension}'



class Vehicle(models.Model):
    SM = 0
    MD = 1
    LG = 2
    VN = 3
    VEHICLE_CATEGORIES = [
        (SM, 'Small'),
        (MD, 'Medium'),
        (LG, 'Large'),
        (VN, 'Van'),
    ]

    VEHICLE_MODEL = [
        ( 0, 'Other'),
        ( 1, 'Audi'),
        ( 2, 'BMW'),
        ( 3, 'Chevrolet'),
        ( 4, 'Ford'),
        ( 5, 'Honda'),
        ( 6, 'Hyundai'),
        ( 7, 'Jeep'),
        ( 8, 'Kia'),
        ( 9, 'Lexus'),
        ( 10, 'Mazda'),
        ( 11, 'Mercedes-Benz'),
        ( 12, 'Mitsubishi'),
        ( 13, 'Nissan'),
        ( 14, 'Renault'),
        ( 15, 'Suzuki'),
        ( 16, 'Subaru'),
        ( 17, 'Tata'),
        ( 18, 'Toyota'),
        ( 19, 'VolksWagen'),
        ( 20, 'Volvo'),
    ]

    owner           = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vehicel_owner')
    model_name      = models.IntegerField(choices=VEHICLE_MODEL, default=0)
    model_year      = models.DateField(blank=True, null=True)
    reg_no          = models.CharField(max_length=20, unique=True)
    vehicle_type    = models.IntegerField(choices=VEHICLE_CATEGORIES, default=SM)
    added_on        = models.DateField(auto_now_add=True)
    rent            = models.PositiveIntegerField(default = 2000)
    capacity        = models.PositiveIntegerField(default=2)
    is_freezed      = models.BooleanField(default=False)
    is_approved     = models.BooleanField(default=False)
    is_booked       = models.BooleanField(default=False)
    booked_date     = models.DateTimeField( auto_now=True, blank=True, null=True)
    is_hired        = models.BooleanField(default=False)
    image           = models.ImageField(default='default_vehicle.png', upload_to =photo_path)

    class Meta:
        ordering = ['-is_approved','-added_on']


    def get_absolute_url(self):
        return reverse_lazy('vehicle:detail_vehicle', kwargs={'pk': self.pk})


    def approve_vehicle(self):
        self.is_approved = not self.is_approved
        self.save()

    def freeze_vehicle(self):
        self.is_freezed = not self.is_freezed
        self.save()


    def save(self, *args, **kwargs):
        super(Vehicle, self).save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 350:
            output_size = (400, 450)
            img.thumbnail(output_size)
            img.save(self.image.path)


    @staticmethod
    def hire_vehicle(self):
        self.is_hired = not self.is_hired
        self.save()


    @staticmethod
    def booked(self):
        self.is_booked  = True
        self.booked_date = datetime.datetime.now()
        self.save()

    @staticmethod
    def unbook(self):
        self.is_booked  = False
        self.booked_date = datetime.datetime.now()
        self.save()


    def __str__(self):
        return  self.reg_no
        

app/fleet/views.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django.shortcuts import (render, get_object_or_404, redirect, reverse)
from django.http import (HttpResponseRedirect, HttpResponse)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from uuid import uuid4
from datetime import (datetime, date)

from users.models import Profile
from .models import (Fleet, Transaction)
from vehicle.models import Vehicle

import io
from reportlab.pdfgen import canvas
from django.http import FileResponse

import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


# Logged in Users Fleet List View
@login_required
def fleet_view(request):
    template                    = 'fleet/fleets.html'
    req_user                    = request.user.user_profile
    fleets                      = Fleet.objects.filter(user = req_user)
    context                     = {
        'fleets': fleets,
    }
    return render(request, template, context)


# Admins View of all fleets
@login_required
def admin_fleet_view(request):
    template                    = 'fleet/fleet_admin.html'
    req_user                    = request.user.user_profile
    fleets                      = Fleet.objects.filter()
    context                     = {
        'fleets': fleets,
    }
    return render(request, template, context)


# Certain fleet detail view
@login_required
def fleet_detail_view(request, pk, car_pk=None):
    template            = 'fleet/fleet_detail.html'
    fleet               = get_object_or_404(Fleet, pk = pk)
    request.session['fleet_id'] = fleet.id
    car                 = ''
    if car_pk:
        car                 = get_object_or_404(Vehicle, pk = car_pk)
    context             = {
        'fleet': fleet,
        'vehicles' : fleet.get_fleet_vehicles(),
        'total': fleet.get_total(),
        'car': car
    }
    return render(request, template, context)


# Activating existing fleet for modification
@login_required
def existing_fleet(request, pk):
    fleet               = get_object_or_404(Fleet, pk = pk)
    request.session['fleet_id'] = fleet.id
    return redirect('vehicle:vehicle_list')


# Creating new fleet for Vehicle booking
def new_fleet(request):
    fleet = Fleet.objects.create(user = request.user.user_profile, fleet_ref = str(uuid4())[-6:].upper())
    messages.info(request, f'Please !!.. Select vehicle for your Fleet')
    request.session['fleet_id'] = fleet.id
    return redirect('vehicle:vehicle_list')


# Adding vehicle to the fleet
@login_required
def add_to_fleet(request, pk):
    user                        = request.user.user_profile
    fleet_id                    = request.session.get('fleet_id', None)
    car                         = get_object_or_404(Vehicle, pk = pk)
    fleet                       = ''
    if fleet_id is None:
        fleet = Fleet.objects.create(user = user, fleet_ref = str(uuid4())[-6:].upper())
        fleet.vehicles.add(car)
        car.booked(car)
        messages.info(request, f'{car.reg_no} added to fleet {fleet.fleet_ref}')
        request.session['fleet_id'] = fleet.id
    else:
        fleet                   = get_object_or_404(Fleet, pk = fleet_id)
        if fleet.is_purchased:
            messages.warning(request, f'Cannot modify this Fleet. Please register new Fleet.')
        elif fleet.vehicles.count() >= 10:
            messages.warning(request, f'You have reached the limit of 10')
        elif not fleet.user == user:
            messages.success(request, f'You cannot modify this Fleet')
        elif fleet.vehicles.count == 11:
            messages.info(request, f'You have reached the max number vehicle for a fleet')
        else:
            fleet.vehicles.add(car)
            car.booked(car)
            messages.info(request, f'{car.reg_no} added to fleet {fleet.fleet_ref}')
    
    return HttpResponseRedirect(fleet.get_absolute_url())


# Removing vehicle form the fleet
@login_required
def remove_from_fleet(request, fleet_pk, vehicle_pk):
    car             = get_object_or_404(Vehicle, pk = vehicle_pk)
    fleet           = get_object_or_404(Fleet, pk = fleet_pk)
    if request.user.is_staff or request.user.user_profile == fleet.user:
        car.is_hired = False
        car.is_booked = False
        car.save()
        fleet.vehicles.remove(car)
        messages.info(request, f'{car.reg_no} removed form the Fleet')
    else:
        messages.error(request, 'You cannot perform vehicle remove action on this fleet')

    return HttpResponseRedirect(fleet.get_absolute_url())


# Cancel a fleet
@login_required
def cancel_fleet(request, pk):
    fleet      = get_object_or_404(Fleet, pk=pk)
    if fleet.user == request.user.user_profile or request.user.is_staff:
        fleet_vhicles                       = fleet.vehicles.all()
        fleet_vhicles.update( is_hired=False )
        fleet.delete()
        del request.session['fleet_id']
    else:
        messages.error(request, 'You cannot perform this action on this fleet')
        return HttpResponseRedirect(fleet.get_absolute_url())

    return HttpResponseRedirect(reverse('fleet:fleets'))


# Removing a fleet
@login_required
def remove_fleet(request, pk):
    fleet           = get_object_or_404(Fleet, pk = pk)
    if request.user.user_profile == fleet.user:
        Fleet.delete(fleet)
        messages.info(request, f'{fleet.fleet_ref} removed')
        del request.session['fleet_id']
    else:
        fleet.delete()
        messages.error(request, 'You cannot perform this action on this fleet')

    if request.user.is_staff:
        return HttpResponseRedirect(reverse('fleet:admin_fleet_view'))
    else:
        return redirect ('fleet:fleets')



# Approving fleet (Admin)
@login_required
def approve_fleet(request, pk):
    if not request.user.is_staff:
        messages.error(request, 'You cannot perform this action on this fleet')
        return HttpResponseRedirect(fleet.get_absolute_url())
    fleet      = get_object_or_404(Fleet, pk=pk)
    fleet_vhicles                       = fleet.vehicles.all()
    fleet_vhicles.update( is_booked = False )
    fleet.approved_on = datetime.now()
    fleet.approve()

    # Send Mail After Fleet Approval
    send_mail('Fleet Approved',
        f'Your fleet {fleet.fleet_ref} has ' +
        f'been approved, Your fleet will be active until {fleet.expiration_date().date()} .',
        'randomfahad@gmail.com', [fleet.user.user.email], fail_silently=False )

    return HttpResponseRedirect(reverse('fleet:admin_fleet_view'))


# Block a Fleet 
@login_required
def freeze_fleet(request, pk):
    if not request.user.is_staff:
        messages.error(request, 'You cannot perform this action on this fleet')
        return HttpResponseRedirect(fleet.get_absolute_url())
    fleet      = get_object_or_404(Fleet, pk=pk)
    fleet.is_freezed = not fleet.is_freezed
    fleet.save()
    return HttpResponseRedirect(reverse('fleet:admin_fleet_view'))

# Check-out by paying for Fleet
@login_required
def checkout(request, pk):
    template = 'fleet/payment.html'
    fleet_to_pay                    = get_object_or_404(Fleet, pk = pk)
    total = fleet_to_pay.get_total()

    if fleet_to_pay.check_hired():
        messages.warning (request, 'Already Hired vehicle\'s In the Fleet')
        return HttpResponseRedirect(fleet_to_pay.get_absolute_url())
    elif request.user.user_profile != fleet_to_pay.user:
        messages.warning (request, 'You cannot pay for other people\'s fleet.')
    elif request.method == 'POST':
        token = request.POST['stripeToken']
        charge = stripe.Charge.create(
            amount= total,
            currency='usd',
            description='Example charge',
            source=token,
        )
        return redirect(reverse ('fleet:update_record', kwargs = {'pk':fleet_to_pay.pk,'token': token}))

    context = {
        'fleet': fleet_to_pay
    }
    return render(request, template, context)
     

# After successfull payment Store payment information
@login_required
def update_payment_record(request, pk, token):
    fleet_purchased                   = get_object_or_404(Fleet, pk = pk)
    fleet_purchased.is_purchased      = True
    fleet_purchased.booked_date       = datetime.now()
    fleet_vehicles                      = fleet_purchased.vehicles.all()
    fleet_vehicles.update(is_hired = True, is_booked = False)
    fleet_purchased.save()

    transaction = Transaction( profile         = request.user.user_profile,
                            fleet           = fleet_purchased,
                            amount          = fleet_purchased.get_total(),
                            token           = token )
    transaction.save()

    # On successful payment send mail to the user
    send_mail('Payment Success',
            f'Payment for fleet {fleet_purchased.fleet_ref} has ' +
            f'been successfully received, Payement confirmation token {token}.',
            'randomfahad@gmail.com', [fleet_purchased.user.user.email], fail_silently=True )

    # Success message.
    messages.success(request, 'Your payment has been done successfully')
    # Redirecting to the fleet
    return HttpResponseRedirect(fleet_purchased.get_absolute_url())



# Generate Fleet Invoice Only after it is paid
def report_generator(request, pk):


    fleet           = get_object_or_404(Fleet, pk= pk)
    payments        = Transaction.objects.filter(fleet=fleet)
    vehicles        = fleet.vehicles.all()

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)
    p.setLineWidth(.3)
    p.setFont('Helvetica', 12)

    # Center Text
    p.setFont('Helvetica', 18, leading=None )
    p.drawString(240, 790, 'Budget Car Hire' )
    p.drawString(240, 540, 'Vehicle(s) Detail' )
    p.setFont('Helvetica', 12, leading=None )
    p.drawString(250, 765, 'Fleet Detail Report' )
    # Left Side Information
    p.drawString(30, 730, f'Customer Name : {fleet.user.user.username}' )

app/fleet/templates/fleet/fleet_admin.html
{% extends 'fleet/fleet_base.html' %}

{% block fleet_content %}

<div class="p-5">
        <table id="table_id" class="display table">
            <thead>
                <tr>
                    <th>Customer</th>
                    <th>Fleet ID</th>
                    <th>Total vehicles</th>
                    <th>Rent</th>
                    <th>Payment State</th>
                    <th>Approved On</th>
                    <th>Expires On</th>
                    <th ></th>
                </tr>
            </thead>
            <tbody>
{% if fleets %}
{% for fleet in fleets%}
                    <tr>
                        <td><i class="fa fa-user"></i> {{fleet.user.user.username}}</td>
                        <td>{{fleet.fleet_ref}}</td>
                        <td>{{fleet.vehicles.count}}</td>
                        <td>&#2547; {{ fleet.get_total}}</td>
                        <td>{% if fleet.is_purchased %} <span class="btn badge badge-success badge-pill">  Paid </span>{% else %} <span class="btn badge badge-danger badge-pill"> Not-Paid </span>{% endif %}</td>
                        <td> {% if fleet.is_approved %} {{ fleet.approved_on|date:"d M Y" }} {% else %} Not Approved  {% endif %}</td>
                        <td> {% if fleet.is_approved %} {{ fleet.expiration_date|date:"d M Y" }} {% else %} Not Approved {% endif %} </td>
                        <td>
                            <div class="btn-group">
                                {% if not fleet.is_purchased or not fleet.is_approved %}
                                    {% if fleet.is_purchased %}
                                        <a class="btn btn-success" href="{% url 'fleet:approve_fleet' fleet.pk %}">Approve</a>
                                    {% endif %}
                                    <a class="btn btn-danger" href="{% url 'fleet:remove_fleet' fleet.pk %}">Remove</a>
                                {% elif not fleet.is_freezed %}
                                    <a class="btn btn-warning" href="{% url 'fleet:freeze_fleet' fleet.pk %}">Freeze</a>
                                {% else %}
                                    <a class="btn btn-success" href="{% url 'fleet:freeze_fleet' fleet.pk %}">Free</a>
                                {% endif %}
                                <a class="btn btn-primary" href="{% url 'fleet:detail_fleet' fleet.pk %}">Details</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
    
</div>
{% endblock %}

app/fleet/templates/fleet/fleet_base.html
{% extends 'base.html' %}

{% block title %} Fleet {% endblock %}

{% block content %}
{% block fleet_content %}
{% endblock fleet_content%}

{% endblock content%}

app/fleet/templates/fleet/fleet_detail.html
{% extends 'fleet/fleet_base.html' %}

{% block fleet_content %}


{% if fleet %}
<div class="container-fluid">
    <div class="row">
    <!-- <div class="px-4 px-lg-0">
     
        <div class="pb-5"> -->
                    {% if car %}
                  <div class="col-md-10 col-lg-4 p-5 bg-white rounded offset-md-1 shadow-sm mb-5">
                      {% include 'vehicle/_detail_vehicle.html' %}
                  </div>
                  <div class="col-md-10 col-lg-6 p-5 bg-white rounded offset-md-1 shadow-sm mb-5">
                        {% else%}
                    <div class="col-md-10 p-5 bg-white rounded shadow-sm mb-5 offset-md-1">
                    {% endif %}
          
                    <!-- Shopping cart table -->
                    <div class="table-responsive">
                        <div class="bg-light px-4 py-3 font-weight-bold d-flex"> 
                          <span> Reference Id: <span class="text-success">{{fleet.fleet_ref}}</span></span>
                          <span class="ml-auto text-success font-weight-bolder">{% if fleet.is_approved %} Approved {% endif %}</span>
                          
                        </div>

                      <table class="table">
                        <thead>
                          <tr>
                            <th scope="col" class="border-0 bg-light">
                              <div class="p-2 px-3 text-uppercase">Vehicle</div>
                            </th>
                            <th scope="col" class="border-0 bg-light">
                              <div class="py-2 text-uppercase">Rent/month</div>
                            </th>
                            <th scope="col" class="border-0 bg-light">
                              <div class="py-2 text-uppercase">Capacity</div>
                            </th>
                            {% if  not fleet.is_purchased %}
                            <th scope="col" class="border-0 bg-light">
                              <div class="py-2 text-uppercase">Remove</div>
                            </th>
                            {% endif %}
                          </tr>
                        </thead>
                        <tbody>
                        {% for car in vehicles %}
                          <tr>
                            <th scope="row" class="border-0">
                              <a href="{% url 'fleet:detail_fleet' fleet.pk car.pk %}">
                              <div class="p-2">
                                <img src="{{ car.image.url }}" alt="" width="70" class="img-fluid rounded shadow-sm">
                                <div class="ml-3 d-inline-block align-middle">
                                  <h5 class="mb-0"> <span class="text-dark d-inline-block align-middle">{{car.get_model_name_display}}</span></h5>
                                    <span class="text-muted font-weight-normal font-italic d-block">Category: {{car.get_vehicle_type_display.upper}}</span>
                                    {% if car.is_hired%} <span class="text-muted font-weight-normal font-italic d-block text-danger">This Vehicle is Hired</span>{% endif %}
                                </div>
                              </div>
                            </a>
                            </th>
                            <td class="border-0 align-middle"><strong>&#2547; {{car.rent}} /-</strong></td>
                            <td class="border-0 align-middle"><strong>{{car.capacity}}</strong></td>
                            {% if not car.is_hired or not fleet.is_purchased %} 
                              <td class="border-0 align-middle"> <a href="{% url 'fleet:remove_from_fleet' fleet.pk car.pk %}" class="text-dark"><i class="fa fa-trash text-danger"></i></a> </td>
                            {% endif %}
                          </tr>
                        {% endfor %}
                            <tr class="table-active">
                            <th scope="row" class="border-0">
                              <h5>Total Vehicels: {{fleet.vehicles.count}}</h5>
                            </th>
                            <td class="border-0 align-middle"> <span class="h5">Total Rent: </span></td>
                            <td class="border-0 align-middle"><span class="h5">&#2547; {{total}} /-</span></td>
                          {% if  not fleet.is_purchased %}
                            <td class="border-0 align-middle"></td>
                            {% endif %}
                          </tr>

                        </tbody>
                      </table>
                      {% if not fleet.is_purchased and fleet.vehicles.count < 10 %}
                        <a href="{% url 'fleet:existing_fleet' fleet.pk %}" id="button-addon3" class="btn btn-success btn-block px-4 rounded-pill"><i class="fa fa-gift mr-2"></i>Add Vehicles</a>
                      {% elif fleet.is_purchased or fleet.vehicles.count >= 10 %}
                      <span class="text-warning h3 text-center" >Reached Vehicles Limit of 10 For A Fleet</span>
                      <a href="{% url 'fleet:new_fleet' %}" id="button-addon3" class="btn btn-primary btn-block px-4 rounded-pill"><i class="fa fa-gift mr-2"></i>New Fleet</a>
                      {% endif %}
                    </div>
                    <!-- End -->
                  </div>
                </div>

                <div class="col-md-10 col-lg-6 offset-md-1">
                  <div class="bg-light rounded-pill px-4 py-3 text-capitalize font-weight-bold">Fleet information </div>
                  <div class="p-4">
                  <p class=" mb-4"><span class="ml-auto">
                    {% if fleet.is_approved %}
                      <span class="text-warning h4">Expirs on: {{ fleet.expiration_date|date:"d-M-Y" }}</span>
                    {% else %}
                      <span class="text-primary"> Your fleet will be expired after 30 days from the approval day</span>
                    {% endif %}
                  </p>
                  <ul class="list-unstyled mb-4">
                      <li class="d-flex justify-content-between py-3 border-bottom">
                        <strong class="text-muted">Total Vehicle(s):</strong>
                        <strong class="font-weight-bold">	
                            {{fleet.vehicles.count}}
                          </strong>
                          </li>
                        <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total Rent:</strong>
                        <h5 class="font-weight-bold">&#2547; {{total}}</h5>
                      </li>
                    </ul>
                    {% if not fleet.is_purchased %}
                      <a href="{% url 'fleet:checkout' fleet.pk  %}" class="btn btn-info rounded-pill py-2 btn-block">Procceed to checkout</a>
                      <a href="{% url 'fleet:cancel_fleet' fleet.pk  %}" class="btn btn-warning rounded-pill py-2 btn-block text-dark">Cancel Fleet</a>
                    {% elif fleet.is_purchased %}
                      <a href="{% url 'fleet:report_generator' fleet.pk  %}" class="btn btn-info rounded-pill p-3 btn-block">Fleet Report</a>
                    {% else %}
                      <p class="h5 text-danger" >Collect Your Invoice After Payment</p>
                    {% endif %}
                  </div>
                </div>
<!-- 
        </div>
      </div> -->





{% else %}
    Sorry!!!!      No Fleets
    <br>
    {{msg}}
{% endif %}

                      </div>
          </div>
{% endblock fleet_content%}

app/fleet/templates/fleet/fleets.html
{% extends 'fleet/fleet_base.html' %}
{% block fleet_content %}
      
<div class="container">
    <div class="row">
{% if fleets%}

        
    {% for fleet in fleets %}
    <div class="card px-5 h4">
    <p class="card-header ">
        Fleet ID: <span class="font-weight-bolder h4 text-success">{{ fleet.fleet_ref }}</span>
    </p>
    <div class="card-body p-5">
            <div class="text-capitalize">
                <span>Total Cars:</span>
                <span>{{ fleet.vehicles.count }}</span>
            </div>
            <hr class="my-3 bg-primary" >
            {% if fleet.is_approved %}
            <div class="text-capitalize">
                <span>Expires on:</span>
                <span class="text-danger">{{ fleet.expiration_date|date:"d-M-Y" }}</span>
            </div>
            <hr class="my-3 bg-primary" >
            {% endif %}
            <div class="text-capitalize">
                <span>Total Rent:</span>
                <span>&#2547; {{ fleet.get_total }}</span>
            </div>
    </div>
    <div class="card-footer">
        <div class="btn-group">
            <a class="btn btn-lg badge-info" href="{% url 'fleet:detail_fleet'  fleet.pk %}">Detail</a>
        {% if not fleet.is_approved and not fleet.is_purchased %}
            <a class="btn btn-lg badge-danger" href="{% url 'fleet:remove_fleet'  fleet.pk %}">Delete</a>
        {% endif %}
</div>
    </div>
</div>
    {% endfor %}
{% else %}
<!-- Jumbotron -->
<div class="jumbotron p-5 text-center mt-5">

        
      
            <!-- Title -->
            <h3 class="card-title h3 my-4"><strong>You have no Fleets</strong></h3>
            <!-- Text -->
            <!-- Button -->
            <a href="{% url 'fleet:new_fleet' %}" class="btn purple-gradient badge-pill mb-4 px-5">Create New Fleet</a>

      
      </div>
      <!-- Jumbotron -->
{% endif %}

    </div>
</div>

{% endblock fleet_content%}