app/blog/urls.py
from django.urls import path
from django.core.exceptions import PermissionDenied
from . import views

def staff_user(function):
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied
    return wrap



app_name = 'blogs'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('admin-view/', views.admin_blog_list, name='admin_blog_list'),
    path('create/', views.write_blog_view, name='blog_create'),
    path('<int:pk>/detail', views.blog_detail, name='blog_detail'),
    path('admin-view/<int:pk>/detail', views.admin_blog_detail, name='admins_blog_detail'),
    path('<int:pk>/update', views.blog_update_view, name='blog_update'),
    path('<int:pk>/delete', views.blog_delete, name='blog_delete'),
    path('<int:pk>/approve', views.blog_approval, name='blog_approval'),
    path('comment/<int:pk>/comment', views.create_comment, name='add_blog_comment'),
    path('comment/<int:pk>/delete', views.comment_delete, name='delete_blog_comment'),
    path('search/', views.search, name='search'),
    path('about-us/', views.about_us, name='about_us'),
]

app/config/urls.py
# Deleveoped
# Fahad Md Kamal
# NCC ID: 00171328



from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('register/', user_views.register, name= 'register'),
    path('profile/', user_views.profile, name= 'profile'),
    path('user-profile/<int:pk>/', user_views.user_detail, name='user_profile' ),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='index.html'), name='logout'),
    path('vehicle/', include('vehicle.urls', namespace='vehicle')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('fleet/', include('fleet.urls', namespace='fleet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse

class Blog(models.Model):
    OT = 0
    VH = 1
    SV = 2
    blog_TOPICS = [
        (OT, 'Others'),
        (VH, 'Vehicle'),
        (SV, 'Service'),
    ]
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField (max_length=250)
    content = models.TextField(max_length=600)
    topic = models.IntegerField(choices=blog_TOPICS, default=OT)
    posted_date = models.DateTimeField(auto_now_add=True)
    is_approved = models.BooleanField(default=False)


    def __str__(self):
        return self.title

    @staticmethod
    def approve(self):
        self.is_approved = not self.is_approved
        self.save()
        
        
    def get_absolute_url(self):
        return reverse('blogs:blog_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-posted_date','-is_approved']


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE, related_name="user_comment")
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name="comments")
    comment = models.TextField(max_length= 256)
    comment_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('blogs:blog_detail', kwargs={'pk': self.blog.pk})

    class Meta:
        ordering = ['-comment_date',]

app/blog/forms.py
from django import forms
from . import models





class comment_form(forms.ModelForm):
    
    class Meta():
        model = models.Comment
        fields = ('comment',)

        widgets = {
            'comment': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Write Comment'})
        }


class blog_form(forms.ModelForm):

    class Meta:
        model = models.Blog
        fields = ('title', 'content', 'topic')

        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Blog Title'}),
            'content': forms.Textarea (attrs={'class':'form-control', 'placeholder': 'Max 600 words'})
        }

    # def save(self, commit=True):
    #     # blog = self.instance ##  This helps to keep the author
    #     blog_title = self.cleaned_data['title']
    #     blog_content = self.cleaned_data['content']
    #     blog_topic = self.cleaned_data['topic']

app/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from . import models, forms



def about_us(request):
    template = 'blog/about_us.html'
    return render(request, template, {})


#  Show all Blogs
def blog_list(request):
    template = 'blog/blog_list.html'
    blog_list = models.Blog.objects.filter(is_approved=True).order_by('-posted_date')
    page = request.GET.get('page', 1)
    paginator = Paginator(blog_list, 10)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)
    context = {
        'blogs' :  blogs,
        'msg' : 'All Blogs'
        }
    return render(request, template, context=context)



# Show all data for admin
@login_required
def admin_blog_list(request):
    template = 'blog/admin_blog_list.html'
    if not request.user.is_staff:
        messages.warning(request, 'You have no right to visit this page')
        return redirect('home')
    context = {
        'blogs':models.Blog.objects.all()}
    return render (request, template, context) 

@login_required
def admin_blog_detail(request, pk):
    template = 'blog/admin_blog_detail.html'
    if not request.user.is_staff:
        messages.info(request, 'You have no right to visit this page')
        return redirect('home')
    context = {
        'blog':get_object_or_404(models.Blog, pk = pk)}
    return render(request, template, context)


def blog_detail(request, pk):
    template = 'blog/blog_detail.html'
    context = {
        'blog':get_object_or_404(models.Blog, pk = pk),
        'cmt_form': forms.comment_form }
    return render(request, template, context)


@login_required
def write_blog_view(request):
    if request.method == 'POST':
        form = forms.blog_form(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.author = request.user
            blog = form.save()
            return HttpResponseRedirect (reverse ('blogs:blog_detail', kwargs={'pk':blog.id}))
    else:
        form = forms.blog_form()
        context = {
            'form':form,
            'state': 'Create'
            }
        return render(request, 'blog/blog_form.html', context)


@login_required
def blog_update_view(request, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    user = request.user
    if not user == blog.author:
        messages.error(request, 'You are not allowed to update this post')
        redirect('blogs:blog_list')
    if request.method == 'POST':
        form = forms.blog_form(request.POST or None, instance=blog)
        if form.is_valid():
            blog = form.save()
            return HttpResponseRedirect(blog.get_absolute_url())
    else:
        form = forms.blog_form(instance=blog)
    context = {
        'form':form,
        'state': 'Update'
        }
    return render(request, 'blog/blog_form.html', context)


@login_required
def blog_delete(request, pk):
    blog = get_object_or_404(models.Blog, pk=pk)
    user = request.user
    if not user.is_staff or not blog.author == user:
        messages.error(request, 'You cannot perform delete action on this form')
        return HttpResponseRedirect(reverse_lazy('blogs:blog_detail', kwargs={'pk':blog.id}))
    else:
        blog.delete()
        messages.info(request, 'Blog has been deleted, successfully')
        return redirect('blogs:blog_list')
        context = {
            'blog': blog
        }
        return render(request, 'blog/blog_delete.html', context)


@login_required
def create_comment(request, pk):
    blog = get_object_or_404(models.Blog, pk = pk)
    user = request.user
    if request.method == 'POST':
        form = forms.comment_form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.user = user
            comment.save()
            messages.success(request, f'Comment added for - {blog.title} ')
            return redirect('blogs:blog_detail', pk = blog.pk)


@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    blog_pk = comment.blog.pk
    if comment.user == request.user or request.user.is_staff:
        comment.delete()
        messages.success(request, 'Comment Deleted')
    else:
        messages.error(request, 'You are not allowed to delete other peoples comment')
    return redirect('blogs:blog_detail', pk = blog_pk)


@login_required
def blog_approval(request, pk):
    template = 'blog/admin_blog_list.html'
    blog = get_object_or_404(models.Blog, pk=pk)
    if not request.user.is_staff:
        messages.success(request, 'Only Staffs can perform the action')
    blog.approve(blog)
    admin_blog_list(request)
    context = {'blogs':models.Blog.objects.all().order_by('-is_approved')}
    return render (request, template, context) 


def search(request):
    template        = 'blog/blog_list.html'
    blog_list       = models.Blog.objects.filter(is_approved=True)
    query_text      = request.GET.get('query_text', None)

    if query_text   != '' and query_text is not None:
        blogs        = blog_list.filter(Q(title__icontains=query_text) 
                                    | Q(content__icontains=query_text))

    context = {
        'blogs' :  blogs,
        'msg' : f'{blogs.count()} Match(s) Found.'
        }
    return render(request, template, context=context)

app/blog/templates/blog/_list_blog.html
  <!-- Card -->
  <div class="card card-cascade wider my-5 ">
  
        <!-- Card image -->
        <div class="p-3 d-flex view view-cascade gradient-card-header tempting-azure-gradient">
            <img class="rounded-circle blog-img mr-3" src="{{ post.author.user_profile.image.url }}" alt="" srcset="">
        <div class="mt-4">
            <span>@ <a href="{% url 'user_profile' post.author.pk %}"> {{post.author.username}}</a></span>
            <!-- Title -->
          <!-- Text -->
          <p class="text-muted">on: {{ post.posted_date|date:'d-M-Y' }}</p>
        </div>
        </div>
    
        <div class=" card-body">
            <p class="card-title h5 ">{{ post.title }}</p>
            <p class="text-truncate">{{post.content}}</p>
            
      </div>
    
        <div class="card-footer d-flex justify-content-between">
        <div>
          <a class="btn btn-outline-cyan rounded-pill"  href="{% url 'blogs:blog_detail' post.id%}" class="orange-text p-2">
              Read more<i class="fas fa-angle-double-right ml-2"></i>
            </a>
        </div>
        {% if post.comments.count > 0 %}
      <div class="ml-auto mt-3">
          <a class="card-title text-decoration-none ml-auto" href="{% url 'blogs:blog_detail' post.id%}">
              <span class="badge badge-success badge-pill ml-3">{{post.comments.count}}</span> Comment(s)
          </a>
        </div>
        {% endif %}
      </div>
      </div>
      <!-- Card -->

app/blog/templates/blog/admin_blog_detail.html
{% extends 'blog/blog_base.html' %}
{% load crispy_forms_tags %}

{% block blog_content%}


  <!--Main layout-->
  <main class="mt-5 pt-5">
        <div class="container">
    
          <!--Section: Post-->
          <section class="mt-4">
    
            <!--Grid row-->
            <div class="row">
    
              <!--Grid column-->
              <div class="col-md-8 mb-4">
                <!--Card-->
                <div class="card mb-4 wow fadeIn">
    
                  <!--Card content-->
                  <div class="card-body">
                    <blockquote class="blockquote">
                      <p class="mb-0">{{ blog.title }}</p>
                      <footer class="blockquote-footer">by @ <a href="{% url 'user_profile' blog.author.pk %}">{{ blog.author }}</a><br>
                        <cite title="Source Title">{{ blog.posted_date }}</cite>
                      </footer>
                    </blockquote>
    
                    <p>{{ blog.content }}</p>
    
                  </div>
                <div class="card-footer">
                    <div>
                        <a class="btn btn-outline-success mr-auto" href="{% url 'blogs:blog_update' blog.pk %}">Edit Post</a>
                        <a class="btn btn-outline-danger" href="{% url 'blogs:blog_delete' blog.pk %}">Delete Post</a>
                    </div>
                </div>
                </div>
                <!--/.Card-->
    
                <!--Card-->
                <div class="card mb-4 wow fadeIn">
    
                  <div class="card-header font-weight-bold">
                    <span>About author</span>
                    <span class="pull-right">
                      <a href="">
                        <i class="fab fa-facebook-f mr-2"></i>
                      </a>
                      <a href="">
                        <i class="fab fa-twitter mr-2"></i>
                      </a>
                      <a href="">
                        <i class="fab fa-instagram mr-2"></i>
                      </a>
                      <a href="">
                        <i class="fab fa-linkedin-in mr-2"></i>
                      </a>
                    </span>
                  </div>
    
                  <!--Card content-->
                  <div class="card-body">
    
                    <div class="media d-block d-md-flex mt-3">
                      <a href="{% url 'user_profile' blog.author.pk %}"> 
                        <img class="d-flex mb-3 mx-auto z-depth-1" src="{{ blog.author.user_profile.image.url }}"
                        alt="Generic placeholder image" style="width: 100px;">
                      <div class="media-body text-center text-md-left ml-md-3 ml-0">
                        <h5 class="mt-0 font-weight-bold">{{ blog.author }}
                        </h5>
                        {{blog.author.profile.first_name}}
                      </div>
                      </a>
                    </div>
    
                  </div>
    
                </div>
                <!--/.Card-->

                <!--Comments-->
                <div class="card card-comments mb-3 wow fadeIn">
                  <div class="card-header font-weight-bold"> comment(s)</div>
                  <div class="card-body">
    
                <div class="media d-block d-md-flex mt-4">
                      <img class="d-flex mb-3 mx-auto " src="" alt="Generic placeholder image">
                      <div class="media-body text-center text-md-left ml-md-3 ml-0">
                        <h5 class="mt-0 font-weight-bold">
                                <small class="text-muted"></small>
                          <a href="" class="pull-right">
                            <i class="fas fa-reply"></i>
                          </a>
                        </h5>
                        <div class="card-footer">
                                <a class="btn btn-danger" href="">Delete Comment</a>
                            </div>
                        
    

                      </div>
                    </div>
  
                  </div>
                </div>
                <!--/.Comments-->
    

              </div>
              <!--Grid column-->
    
              <!--Grid column-->
              <div class="col-md-4 mb-4">

                <!--Card-->
                <div class="card mb-4 wow fadeIn">
    
                  <div class="card-header">Related blogs</div>
    
                  <!--Card content-->
                  <div class="card-body">
    
                    <ul class="list-unstyled">
                      <li class="media">
                        <div class="media-body">
                          <a href="">
                            <h5 class="mt-0 mb-1">Vehicle Post</h5>
                          </a>
                          
                        </div>
                      </li>
                      <li class="media my-4">
                        <div class="media-body">
                          <a href="">
                            <h5 class="mt-0 mb-1">Latest Post</h5>
                          </a>
                          
                        </div>
                      </li>
                      <li class="media">
                        <div class="media-body">
                          <a href="">
                            <h5 class="mt-0 mb-1">Other post</h5>
                          </a>
                          
                        </div>
                      </li>
                    </ul>
    
                  </div>
    
                </div>
                <!--/.Card-->
    
              </div>
              <!--Grid column-->
    
            </div>
            <!--Grid row-->
    
          </section>
          <!--Section: Post-->
    
        </div>
      </main>
      <!--Main layout-->

{% endblock  %}

app/blog/templates/blog/admin_blog_list.html
{% extends 'blog/blog_base.html' %}
{% load crispy_forms_tags %}

{% block blog_content%}
<div class="container">
        <!-- row -->
        <div class="row">
{% if user.is_staff %}

<table id="table_id" class="display my-5">
        <thead>
            <tr>
                <th>Author</th>
                <th>Title</th>
                <th>Topic</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% if blogs %}
                {% for blog in blogs %}
                    <tr>
                        <td>{{ blog.author }}</td>
                        <td>{{ blog.title }}</td>
                        <td>{{ blog.get_topic_display }}</td>
                        <td>
                            <div class="btn-group"> 
                                {% if not blog.is_approved%}
                                    <a class="btn btn-success" href="{% url 'blogs:blog_approval' blog.pk %}">Approve</a>
                                {% else%}
                                    <a class="btn btn-warning" href="{% url 'blogs:blog_approval' blog.pk %}">Block</a>
                                {% endif %}
                                <a class="btn btn-primary" href="{% url 'blogs:admins_blog_detail' blog.pk %}">Detail</a>
                                <a class="btn btn-danger" href="{% url 'blogs:blog_delete' blog.pk %}">Delete</a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            {% endif %}
        </tbody>
    </table>

{% else %}
    <p class="display-1">You don't have permission</p>
{% endif %}
</div>
</div>

{% endblock blog_content%}
  

app/blog/templates/blog/blog_base.html
{% extends 'base.html' %}

{% block title %} Blogs {% endblock %}

{% block content %}

<!-- <div class="container"> -->
  <!-- <div class="row"> -->
    {% block blog_content%}
    {% endblock %}
  <!-- </div> -->
<!-- </div> -->
{% endblock content %}

app/blog/templates/blog/blog_delete.html
{% extends 'blog/blog_base.html' %}

{% block blog_content%}
    <div  class="jumbotron col-sm-12 col-md-8 col-xl-8 offset-md-2 col-xl-2 mt-5">
        <p class="display-4 text-danger"> Warning !! </p>
        <p class="lead text-muted"> Do you really want to Delete the Blog ? </p>
        <hr class="my-4 bg-light" >
        <p class=""><span class="h5">Title:</span> {{ blog.title}}</p>
        <hr class="my-4 bg-light" >
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-lg btn-danger" type="submit">Delete</button>
            <a class="btn btn-lg btn-success" href="{% url 'blogs:blog_detail' blog.pk %}">Cancel</a>
    </form>
    </div>
{% endblock  %}

app/blog/templates/blog/blog_detail.html
{% extends 'blog/blog_base.html' %}
{% load crispy_forms_tags %}

{% block blog_content%}

  <!--Main layout-->
  <main class="mt-5 pt-5">
        <div class="container">
    
          <!--Section: Post-->
          <section class="mt-4">
    
            <!--Grid row-->
            <div class="row">
    
              <!--Grid column-->
              <div class="col-md-8 mb-4">
                <!--Card-->
                <div class="card mb-4 wow fadeIn">
    
                  <!--Card content-->
                  <div class="card-body">
    
                    <blockquote class="blockquote">
                      <p class="mb-0">{{ blog.title }}</p>
                      <footer class="blockquote-footer">by @ <a href="{% url 'user_profile' blog.author.pk %}">{{ blog.author }} </a><br>
                        <cite title="Source Title">{{ blog.posted_date }}</cite>
                      </footer>
                    </blockquote>
    
                    <p>{{ blog.content }}</p>
    
                  </div>
                <div class="card-footer">
                    {% if user.is_authenticated %}
                        {% if user.id == blog.author.id %}
                        <div>
                            <a class="btn btn-outline-success mr-auto" href="{% url 'blogs:blog_update' blog.pk %}">Edit Post</a>
                            <a class="btn btn-outline-danger" href="{% url 'blogs:blog_delete' blog.pk %}">Delete Post</a>
                        </div>
                        {% endif %}
                    {% endif %}
                </div>
                </div>
                <!--/.Card-->
    
                <!--Card-->
                <div class="card mb-4 wow fadeIn">
    
                  <div class="card-header font-weight-bold">
                    <span>About author</span>
                    <span class="pull-right">
                      <a href="https://www.facebook.com" target="_blank">
                        <i class="fab fa-facebook-f mr-2"></i>
                      </a>
                      <a href="https://www.twitter.com" target="_blank">
                        <i class="fab fa-twitter mr-2"></i>
                      </a>
                      <a href="https://www.instagram.com" target="_blank">
                        <i class="fab fa-instagram mr-2"></i>
                      </a>
                      <a href="https://www.linkedin.com" target="_blank">
                        <i class="fab fa-linkedin-in mr-2"></i>
                      </a>
                    </span>
                  </div>
    
                  <!--Card content-->
                  <div class="card-body">
    
                    <div class="media d-block d-md-flex mt-3">
                   <a href="{% url 'user_profile' blog.author.pk %}"> <img class="d-flex mb-3 mx-auto z-depth-1" src="{{ blog.author.user_profile.image.url }}"
                        alt="Generic placeholder image" style="width: 100px;">
                      <div class="media-body text-center text-md-left ml-md-3 ml-0">
                        <h5 class="mt-0 font-weight-bold">{{ blog.author }}
                        </h5>
                        {{blog.author.profile.first_name}}
                      </div>
                    </a>
                    </div>
    
                  </div>
    
                </div>
                <!--/.Card-->

                <!--Comments-->
                {% if blog.comments.all %} 
                <div class="card card-comments mb-3 wow fadeIn">
                  <div class="card-header font-weight-bold">{{blog.comments.count}} comment(s)</div>
                  <div class="card-body">
    
                {% for cmt in blog.comments.all %}
                <div class="media d-block d-md-flex mt-4">
                      <img class="d-flex mb-3 mx-auto " src="{{ cmt.user.user_profile.image.url }}" alt="Generic placeholder image">
                      <div class="media-body text-center text-md-left ml-md-3 ml-0">
                        <h5 class="mt-0 font-weight-bold">@ <a href="{% url 'user_profile' cmt.user.pk %}">{{cmt.user.username}}</a>
                                <small class="text-muted">{{cmt.comment_date}}</small>
                          <!-- <a href="" class="pull-right">
                            <i class="fas fa-reply"></i>
                          </a> -->
                        </h5>
                        {{cmt.comment}}
                        {% if user.id == cmt.user.id or user.is_staff %}
                        <div class="mt-5">
                                <a class="btn btn-danger rounded-pill" href="{% url 'blogs:delete_blog_comment' cmt.pk %}">Delete</a>
                            </div>
                            {% endif %}
                        
    

                      </div>
                    </div>
                    {% endfor %}
  
                  </div>
                </div>
                {% endif %}
                <!--/.Comments-->
    
                <!--Reply-->
                <div class="card mb-3 wow fadeIn">
                  <div class="card-header font-weight-bold">Leave a reply</div>
                  <div class="card-body">
    
                    <!-- Default form reply -->
                    <form action="{% url 'blogs:add_blog_comment' blog.pk %}" method="post">
                            {% csrf_token %}
                            {{ cmt_form|crispy }}
                            <button type="submit" class="btn btn-success mr-2">Submit</button>
                        </form>
    
                    <!-- Default form reply -->
    
    
    
                  </div>
                </div>
                <!--/.Reply-->
    
              </div>
              <!--Grid column-->
    
              <!--Grid column-->
              <div class="col-md-4 mb-4">

                <!--Card-->
                <div class="card mb-4 wow fadeIn">
    
                  <div class="card-header">Related blogs</div>
    
                  <!--Card content-->
                  <div class="card-body">
    
                    <ul class="list-unstyled">
                      <li class="media">
                        <div class="media-body">
                          <a href="">
                            <h5 class="mt-0 mb-1">Vehicle Post</h5>
                          </a>
                          
                        </div>
                      </li>
                      <li class="media my-4">
                        <div class="media-body">
                          <a href="">
                            <h5 class="mt-0 mb-1">Latest Post</h5>
                          </a>
                          
                        </div>
                      </li>
                      <li class="media">
                        <div class="media-body">
                          <a href="">
                            <h5 class="mt-0 mb-1">Other post</h5>
                          </a>
                          
                        </div>
                      </li>
                    </ul>
    
                  </div>
    
                </div>
                <!--/.Card-->
    
              </div>
              <!--Grid column-->
    
            </div>
            <!--Grid row-->
    
          </section>
          <!--Section: Post-->
    
        </div>
      </main>
      <!--Main layout-->

{% endblock  %}

app/blog/templates/blog/blog_list.html
{% extends 'blog/blog_base.html' %}

{% block blog_content%}
<div class="container">
  
  <!-- row -->
  <div class="row">

    <!-- Left Side Bar -->
    <div class="col-md-8">
      <!-- If any blog available -->
      {% if blogs%}
          <p class="mt-5 text-center h3 py-3 text-dark card-title tempting-azure-gradient rounded-pill">{{msg}} </p>

          <!-- Load Blog Card for each blog -->
          {% for post in blogs %}
            {% include './_list_blog.html' %}
          {% endfor %}

      {% else %}
            <div class="card card-cascade wider mb-3">
              <p class="card-body">There is no blog to show</p>
            </div>
      {% endif%}
      <!-- If any blog available -->

    <!-- Pagination -->
    {% if blogs.has_other_pages %}
    <nav class="Page navigation">
      <ul class="pagination">
        {% if blogs.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ blogs.previous_page_number }}">&laquo;</a>
          </li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in blogs.paginator.page_range %}
          
        {% if blogs.number == i %}
            <li class="active text-danger">
              <span>{{ i }} 
                <span class="sr-only">(current)</span>
              </span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
          {% endif %}

        {% endfor %}

        {% if blogs.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ blogs.next_page_number }}">&raquo;</a>
          </li>
        {% else %}
          <li class="disabled">
            <span>&raquo;</span>
          </li>
        {% endif %}

      </ul>
    </nav>
    {% endif %}
    <!-- Pagination -->

    </div>
    <!-- Left Side Bar -->

    <!-- Right Side Bar -->
    <div class="col-md-4 my-5">

      <!-- Search card -->
      <div class="card">
          <p class="h3 p-2 text-dark card-title tempting-azure-gradient">
              Search
          </p>

          <!-- Search box -->
          <div class="card-body">
              <form action="{% url 'blogs:search' %}" method="get">
                <input class="form-control" type="text" name="query_text" placeholder="Search ..." >
              <button class="btn btn-block badge-success" type="submit">submit</button>
            </form> 
          </div>
          <!-- Search box -->

      </div>
      <!-- Search card -->

    </div>
    <!-- Right Side Bar -->

  </div>
<!-- row -->

</div>
{% endblock  %}