app/blog/urls.py
from django.urls import path
from django.core.exceptions import PermissionDenied
from . import views

def staff_user(function):
    def wrap(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_staff:
            return function(request, *args, **kwargs)
        else:
            raise PermissionDenied
    return wrap



app_name = 'blogs'

urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('admin-view/', views.admin_blog_list, name='admin_blog_list'),
    path('create/', views.write_blog_view, name='blog_create'),
    path('<int:pk>/detail', views.blog_detail, name='blog_detail'),
    path('admin-view/<int:pk>/detail', views.admin_blog_detail, name='admins_blog_detail'),
    path('<int:pk>/update', views.blog_update_view, name='blog_update'),
    path('<int:pk>/delete', views.blog_delete, name='blog_delete'),
    path('<int:pk>/approve', views.blog_approval, name='blog_approval'),
    path('comment/<int:pk>/comment', views.create_comment, name='add_blog_comment'),
    path('comment/<int:pk>/delete', views.comment_delete, name='delete_blog_comment'),
    path('search/', views.search, name='search'),
    path('about-us/', views.about_us, name='about_us'),
]

app/config/urls.py
# Deleveoped
# Fahad Md Kamal
# NCC ID: 00171328



from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
    path('register/', user_views.register, name= 'register'),
    path('profile/', user_views.profile, name= 'profile'),
    path('user-profile/<int:pk>/', user_views.user_detail, name='user_profile' ),
    path('login/', auth_view.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='index.html'), name='logout'),
    path('vehicle/', include('vehicle.urls', namespace='vehicle')),
    path('blogs/', include('blog.urls', namespace='blogs')),
    path('fleet/', include('fleet.urls', namespace='fleet')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/fleet/urls.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django.urls import path
from . import views

app_name = 'fleet'

urlpatterns = [
       
    path(
        '',
        views.fleet_view,
        name= 'fleets'),

    path(
        'admin-view/',
        views.admin_fleet_view,
        name= 'admin_fleet_view'),
       
    path(
        'detail/<int:pk>/',
        views.fleet_detail_view,
        name= 'detail_fleet'),
       
    path(
        'detail/<int:pk>/<int:car_pk>',
        views.fleet_detail_view,
        name= 'detail_fleet'),
       
    path(
        'add-vehicle/<int:pk>',
        views.add_to_fleet,
        name= 'add_to_fleet'),
       
    path(
        'new-fleet/',
        views.new_fleet,
        name= 'new_fleet'),
       
    path(
        'existing-fleet/<int:pk>/',
        views.existing_fleet,
        name= 'existing_fleet'),
        
    path(
        'remove-vehicle/<int:fleet_pk>/<int:vehicle_pk>',
        views.remove_from_fleet,
        name= 'remove_from_fleet'),
        
    path(
        'cancel-fleet/<int:pk>/',
        views.cancel_fleet,
        name= 'cancel_fleet'),
        
    path(
        'remove-fleet/<int:pk>/',
        views.remove_fleet,
        name= 'remove_fleet'),
        
    path(
        'approve-fleet/<int:pk>/',
        views.approve_fleet,
        name= 'approve_fleet'),
        
    path(
        'freeze-fleet/<int:pk>/',
        views.freeze_fleet,
        name= 'freeze_fleet'),

    path(
        '<int:pk>/', 
        views.checkout, 
        name='checkout' ),

    path(
        'update-record/<int:pk>/<str:token>', 
        views.update_payment_record, 
        name='update_record' ),

    path(
        'report/<int:pk>', 
        views.report_generator, 
        name='report_generator' ),

        
]

app/vehicle/urls.py
# Deleveoped By
# Fahad Md Kamal
# NCC ID: 00171328

from django.urls import path
from . import views

app_name = 'vehicle'

urlpatterns = [
       
    path('',
        views.vehicle_list_view, 
        name= 'vehicle_list'),
    
    path('admin-view/', 
        views.admin_vehicle_view, 
        name= 'admin_vehicle'),
    
    path('owner-view/', 
        views.owner_vehicle_list, 
        name= 'owner_vehicle_list'),
    
    path('search-vehicles/', 
        views.search_vehicle, 
        name= 'search_vehicle'),

    path('register/', 
        views.vehicle_registration, 
        name= 'reg_vehicle'),
    
    path('<int:pk>/', 
        views.vehicle_detail_view, 
        name= 'detail_vehicle'),
    
    path('<int:pk>/approve', 
        views.approve_vehicle, 
        name= 'approve_vehicle'),
    
    path('<int:pk>/freeze', 
        views.freeze_vehicle, 
        name= 'freeze_vehicle'),
    
    path('<int:pk>/update/', 
        views.vehicle_update_view, 
        name= 'update_vehicle'),
    
    path('<int:pk>/delete/', 
        views.vehicel_delete_view, 
        name= 'delete_vehicle'),
]

app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Base Template {% endblock %}</title>
    <link rel="icon" href="{% static 'media/favico.png' %}" >
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <!-- <link rel="stylesheet" href="{ static 'css/bootstrap.min.css' }"> -->
    <!-- <link rel="stylesheet" href="{ static 'css/font-awesome.min.css' }"> -->
    <!-- <link rel="stylesheet" href="{ static 'css/mdb.css' }"> -->
    <!-- <link rel="stylesheet" href="{ static 'css/datatable.css' }"> -->


    <!-- Font Awesome -->
    <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"> -->
    <!-- Google Fonts -->
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"> -->
    <!-- Bootstrap core CSS -->
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"> -->
    <!-- Material Design Bootstrap -->
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/css/mdb.min.css" rel="stylesheet"> -->



    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">



    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
<body>

{% include 'nav.html' %}


<div class="container my-2 main-container">

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    {% endif %}
  </div>

    {% block content%}
    {% endblock %}

{% include 'footer.html' %}



    <!-- JQuery -->
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script> -->
    <!-- Bootstrap tooltips -->
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script> -->
    <!-- Bootstrap core JavaScript -->
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script> -->
    <!-- MDB core JavaScript -->
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.15.0/js/mdb.min.js"></script> -->

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/js/mdb.min.js"></script>

    <!-- <script src="{ static 'js/jquery-3.4.1.min.js' }"></script> -->
    <!-- <script src="{ static 'js/bootstrap.min.js' }"></script> -->
    <!-- <script src="{ static 'js/popper.min.js' }"></script> -->
    <!-- <script src="{ static 'js/datatable.js' }"></script> -->
    <!-- <script src="{ static 'js/fontawesome.min.js' }"></script> -->
    <!-- <script src="{ static 'js/mdb.min.js' }"></script> -->
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="{% static 'js/custom.js' %}"></script>
  </body>
</html>

app/templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small bg-secondary my-2">

    <!-- Footer Links -->
    <div class="text-center text-md-left px-5">
  
      <!-- Grid row -->
      <div class="row">
  
        <!-- Grid column -->
        <div class="col-md-3 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-capitilize mt-3 mb-4">Vehicle</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'vehicle:vehicle_list' %}">Vehicles</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->

  
        <!-- Grid column -->
        <div class="col-md-3 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-capitilize mt-3 mb-4">Blogs</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'blogs:blog_list' %}">All Blogs</a>
            </li>
          </ul>
  
        </div>
        <!-- Grid column -->
  
  
        <!-- Grid column -->
        <div class="col-md-3 mx-auto">
  
          <!-- Links -->
          <h5 class="font-weight-bold text-capitilize mt-3 mb-4">Contact Us</h5>
  
          <ul class="list-unstyled">
            <li>
              <a href="{% url 'blogs:about_us' %}">Contact</a>
            </li>

          </ul>
  
        </div>
        <!-- Grid column -->
  
      </div>
      <!-- Grid row -->
  
  
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-light">© 2019 Copyright<span class="text-light h5" > @ Fahad-Md-Kamal (00171328)</span>
    </div>
    <!-- Copyright -->
  
  </footer>
  <!-- Footer -->

app/templates/index.html
{% extends 'base.html' %}
{% block title %} Budget-Car-Hire || Home {% endblock %}


{% block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 offset-md-1">
<!-- Jumbotron -->
<div class="jumbotron p-0">

    <!-- Card image -->
    <div class="view overlay rounded-top">
      <img src="../static/media/landing_page_image.png" class="img-fluid landing-image" alt="Sample image">

    </div>
  
    <!-- Card content -->
    <div class="card-body text-center mb-3">
  
      <!-- Title -->
      <h3 class="card-title display-1 my-4 text-warning"><strong>Budget Car Hire</strong></h3>
      <!-- Text -->
      <p class="card-text h1 py-2 text_style">Your Business Transportation Solution</p>
      <!-- Button -->
      <a href="{% url 'vehicle:vehicle_list' %}" class="btn purple-gradient badge-pill my-4 px-5">V E H I C L E S</a>
  
    </div>
  
  </div>
  <!-- Jumbotron -->
</div>
</div>
</div>


<div class="card">

    </div>



{% endblock content%}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="{% url 'home' %}">BCH</a>
    
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Vehicle
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'vehicle:vehicle_list' %}">All Vehicles</a>
        {% if user.is_authenticated and user.user_profile.user_type == 1 %}
            <a class="dropdown-item" href="{% url 'vehicle:owner_vehicle_list' %}">My Vehicles</a>
            <!-- If the user is Owner only then he can register vehicle -->
          {% if user.user_profile.user_type == 1 %} 
            <a class="dropdown-item" href="{% url 'vehicle:reg_vehicle' %}">Register Vehicle</a>
          {% endif %}

        {% endif %}
        {% if user.is_staff %}
          <a class="dropdown-item" href="{% url 'vehicle:admin_vehicle' %}">Admin View</a>
        {% endif %}
        </div>
        </li>
          {% if user.user_profile.user_type == 0 %} 
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Fleet
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% if not user.is_staff %}
              <a class="dropdown-item" href="{% url 'fleet:fleets' %}">Fleets</a>
              <a class="dropdown-item" href="{% url 'fleet:new_fleet' %}">New Fleet</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'fleet:admin_fleet_view' %}">Admin View</a>
          {% endif %}
        </div>
        </li>
        {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Blog
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'blogs:blog_list' %}">All Blogs</a>
            <a class="dropdown-item" href="{% url 'blogs:blog_create' %}">Write Blog</a>
          {% if user.is_staff %}
          <a class="dropdown-item" href="{% url 'blogs:admin_blog_list' %}">Admin View</a>
          {% endif %}
        </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:about_us' %}">About Us</a>
          </li>
      </ul>
    </div>
    <span class="nav-item dropdown ml-auto mr-3">
        {% if user.is_authenticated %}
        <a id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <img class="user_dp" src="{{ user.user_profile.image.url }}" alt="{{user.username}}-profile-pic">
          </a>
          
        {% else %}
          <a class="nav-link text-light btn-dark-green btn-blue-grey px-3 rounded-circle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i>
          </a>
        {% endif %}
    
        <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          {% if user.is_authenticated %}
          <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="dropdown-item" href="{% url 'login' %}">Login</a>
          <a class="dropdown-item" href="{% url 'register' %}">Join Now</a>
          {% endif %}
        </div>
      </span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
  </nav>